travis:
  secure:
    BINSTAR_TOKEN: k/kWn4EuxqhLD2KGIBHL7MdcR3k0k5qgf+1l/YrunmmN8LcA1iCjTTRH8mdrpghV2Dj5LYyysUx2SXgXyf/fAXg8xIVGhTa5+S8fPE/nzG1oZcqwbSK6G0pA3MELCCylNbblbWyNtkWhs4rwirt32FyiLotms3hQ+UiLdJwwCEdFyndOVBuE+4v8wYdovQJ8suwJYy34WN4+/+QyNNIzU4md7toyiNlD63+5Y46gi9XMBlSInaI6h57BhbJUPDjUwJgTPPmRiXOl2sO2sixQsDeCtD7rev7l9mjdPJk6vRdEbb/gj9JCgsnHHhWCr3tO6WtXhQAS/ZBxIgg3I+wsHfrSgs6T3NsmTkvqvZVhf+8CFyYgghPaZrz8T4HOVZkAJ70xwjr66DY3bjLXFAvgrkF8SxYt2oR1XI9uK+Htr48c0jv2eyQyGfMxQiqnyPS9lFQ5FEqWrnXTRTnA5JPnzAaT0i7OVFZ+tgdJSkiOvLrfpgHvDqSF6G8ULKOrk3wg9r7qQfNTcrtyhMuTeidXnnqVBV6NmL0/q6mlk7QdBYYq6zI29O4n6XTcSFNpNSgl9LKwbeL7N4TainHXZCfb0tBKKLUWeZI9qevKnzWswLHaPNtOmyv4lG19JzPpLruJwtk0eOZl6twHzSNY6c2fCj54wx2EKY+8x/jESXEhV5g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
